### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/Deferred

### ISSUE THREAD

**Issue by fylmr** [STC-VoiceKey/stc-speechkit-android#1]
Hello! 

I've encountered an error while initiating this library with `STCSpeechKit.init` method. It appears that the system can't find the Deferred class: 
```
2020-12-08 17:19:25.900 17915-17915/ru.tele2.mytele2.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.tele2.mytele2.dev, PID: 17915
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/Deferred;
        at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
        at java.lang.reflect.Method.getReturnType(Method.java:148)
        at java.lang.Class.getDeclaredMethods(Class.java:1883)
        at java.lang.reflect.Proxy.getMethodsRecursive(Proxy.java:797)
        at java.lang.reflect.Proxy.getMethods(Proxy.java:786)
        at java.lang.reflect.Proxy.access$300(Proxy.java:239)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:678)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:602)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:438)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:873)
        at retrofit2.Retrofit.create(Retrofit.java:143)
        at ru.speechpro.stcspeechkit.STCSpeechKit.<clinit>(STCSpeechKit.kt:151)
... (stack trace inside application) ...
```

I assume that this might be happening because Coroutines version in my project (1.3.2) is way newer than the version used in the library (0.22.5), and/or because of some code obfuscation issues.

**Comment by fylmr** [comment]
The error is in this line: https://github.com/STC-VoiceKey/stc-speechkit-android/blob/3923d49d6b6a8a0620f8e34d460faca513e464c5/stcspeechkit/src/main/java/ru/speechpro/stcspeechkit/STCSpeechKit.kt#L151

**Comment by prsvic-stc** [comment]
coroutines version updated in revision 05346fba
